Store backups under hostname dir

diff --git a/backup-dbs b/backup-dbs
--- a/backup-dbs
+++ b/backup-dbs
@@ -1,14 +1,21 @@
 #!/usr/bin/env fish
 
+set err "backup-dbs: Error:"
+
+if not set -q hostname
+  echo "$err \$hostname is not set"
+  exit 1
+end
+
 set ts (date "+%Y-%m-%d")
-set dest "/Volumes/Files/Backups/msikma/Databases"
+set dest "/Volumes/Files/Backups/$hostname/Databases"
 set user "root"
 set pass "root"
 set sqlcmd "/Applications/MAMP/Library/bin/mysql"
 set dumpcmd "/Applications/MAMP/Library/bin/mysqldump"
 
 if not test -d "$dest"
-    echo "backup-dbs.fish: Error: could not access destination: $dest"
+    echo "$err could not access destination: $dest"
     exit 1
 end
 
diff --git a/backup-files b/backup-files
--- a/backup-files
+++ b/backup-files
@@ -1,31 +1,37 @@
 #!/usr/bin/env fish
 
-set src \
-"/Users/msikma/Files/" \
-"/Users/msikma/Documents/"
+set err "backup-files: Error:"
 
+if not set -q hostname
+  echo "$err \$hostname is not set"
+  exit 1
+end
+
+set src \
+~/"Files/" \
+~/"Documents/"
 
 set dst \
-"/Volumes/Files/Backups/msikma/Files" \
-"/Volumes/Files/Backups/msikma/Documents"
+"/Volumes/Files/Backups/$hostname/Files" \
+"/Volumes/Files/Backups/$hostname/Documents"
 
 for n in (seq (count $src))
   set s $src[$n]
   set d $dst[$n]
   if not test -d $s
-    echo "Can't access source directory: "$s
-    exit
+    echo "$err Can't access source directory: "$s
+    exit 1
   end
   if not test -d $d
-    echo "Can't access target directory: "$d
-    exit
+    echo "$err Can't access target directory: "$d
+    exit 1
   end
 end
 
 for n in (seq (count $src))
   set s $src[$n]
   set d $dst[$n]
-  echo "Syncing: "$s" -> "$d
+  echo "backup-files: Syncing: "$s" -> "$d
   rsync -ahvrESH8 --delete --progress --stats --exclude=".*/" --exclude=".*" $s $d
 end
 
diff --git a/backup-zoo-music b/backup-zoo-music
--- a/backup-zoo-music
+++ b/backup-zoo-music
@@ -1,17 +1,29 @@
 #!/usr/bin/env fish
-if not test -d "/Volumes/Glitch/"
-  echo "Can't access source directory: /Volumes/Glitch/"
-  exit
-end
-if not test -d "/Volumes/happy zoo/dada/Music"
-  echo "Can't access target directory: /Volumes/happy zoo/dada/Music"
-  exit
+
+set err "backup-zoo-music: Error:"
+set src "/Users/"(whoami)"/Files/Music"
+set dst "/Volumes/happy zoo/dada/Music"
+
+if not set -q hostname
+  echo "$err \$hostname is not set"
+  exit 1
 end
 
-rsync -ahvrESH8 --delete --progress --stats --exclude=".*/" --exclude=".*" "/Volumes/Glitch/Music/Tracker/" "/Volumes/happy zoo/dada/Music/Tracker/"
-rsync -ahvrESH8 --delete --progress --stats --exclude=".*/" --exclude=".*" "/Volumes/Glitch/Music/Game music covers/" "/Volumes/happy zoo/dada/Music/Game music covers/"
-rsync -ahvrESH8 --delete --progress --stats --exclude=".*/" --exclude=".*" "/Volumes/Glitch/Music/Game music/" "/Volumes/happy zoo/dada/Music/Game music/"
-rsync -ahvrESH8 --delete --progress --stats --exclude=".*/" --exclude=".*" "/Volumes/Glitch/Music/Classical/" "/Volumes/happy zoo/dada/Music/Classical/"
+if not test -d $src
+  echo "$err Can't access source directory: $src"
+  exit 1
+end
+
+if not test -d $dst
+  echo "$err Can't access target directory: $dst"
+  exit 1
+end
+
+# Using the old directories anyway. Fix someday.
+rsync -ahvrESH8 --delete --progress --stats --no-links --exclude=".*/" --exclude=".*" "/Volumes/Glitch/Music/Tracker/" "/Volumes/happy zoo/dada/Music/Tracker/"
+rsync -ahvrESH8 --delete --progress --stats --no-links --exclude=".*/" --exclude=".*" "/Volumes/Glitch/Music/Game music covers/" "/Volumes/happy zoo/dada/Music/Game music covers/"
+rsync -ahvrESH8 --delete --progress --stats --no-links --exclude=".*/" --exclude=".*" "/Volumes/Glitch/Music/Game music/" "/Volumes/happy zoo/dada/Music/Game music/"
+rsync -ahvrESH8 --delete --progress --stats --no-links --exclude=".*/" --exclude=".*" "/Volumes/Glitch/Music/Classical/" "/Volumes/happy zoo/dada/Music/Classical/"
 
 mkdir -p ~/.cache/dada
 echo (date +"%a, %b %d %Y %X %z") > ~/.cache/dada/backup-zoo-music
